name: Notify deps2.dev new version

on:
  push:
    branches:
      - main

jobs:
  notify-deps2dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read version from version.txt
      id: get_version
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

    - name: Notify deps2.dev
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "{\"version\": \"${{ env.VERSION }}\"}" https://api.deps2.dev/notify
